name: Disconnected Readiness
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  check:
    uses: carlkyrillos/disconnected-readiness-scorer/.github/workflows/disconnected-readiness-check.yml@feat/add-summary-to-reusable-workflow
    with:
      rules: ""
